apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-12-14T10:13:25Z"
  name: weather-app-service
  namespace: default
  resourceVersion: "5421"
  uid: ac20a07c-4dcd-478d-9484-d6da9ff7f313
spec:
  clusterIP: 10.97.82.39
  clusterIPs:
  - 10.97.82.39
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32210
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: weather-app
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
