name: Install Dependencies
description: 'Install Dependencies'
inputs:
  command-name:
    required: true
    description: Name of Command
    type: string
  npm-command:
    description: run npm Command
    required: true
    type: string
runs:
  using: 'composite'
  steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
        shell: bash
      - name: Run ${{ inputs.command-name}}
        run: ${{ inputs.npm-command }}
        shell: bash