name: Re-build Docker Image
on:
    workflow_dispatch:
    push:
        branches:
            - master
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: Set-up Node
              uses: actions/setup-node@v4
            - name: Install Dependencies
              run: npm ci
            - name: Run Lint
              id: run-lint
              run: npm run lint
            - name: Generate Report
              id: report
              if: success() && steps.run-lint.outcome == 'success'
              run: echo "test"
            