name: Build Image
on:
  workflow_dispatch:
jobs:
    run-npm:
        uses: ./.github/workflows/npm-steps.yml
    docker-build:
        needs: run-npm
        if: success()
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: Build Docker Image
              run: docker build -t weather-app:latest .