name: Build Docker Image
on:
  workflow_call:
jobs:
    run-npm:
        uses: ./.github/workflows/run-npm.yml
    docker-build:
        needs: run-npm
        if: success()
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: Build and publish
              run: |
                docker build -t weather-app:latest .
                docker push ghcr.io/adrn1201/weather-app:latest