name: Npm Run
on: 
    workflow_call:
        inputs:
            command-name:
                required: true
                description: Name of Command
                type: string
            npm-command:
                description: run npm Command
                required: true
                type: string
jobs:
    run-npm:
        runs-on: ubuntu-latest
        steps:
            - name: test
              run: echo "hello"